baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
permalink: :title
markdown: redcarpet

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "package.json"
  - "webpack.config.js"
  - "bs-config.js"
  - "Procfile"
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      is_post: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      is_post: true
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
      is_post: true
