baseurl: ""
permalink: /:title/

title: Shu Uesugi
description: "Shu Uesugi's Personal Site."
gems:
  - jekyll-sitemap
  # Japanese version of the site
  # - jekyll-seo-tag
  - jekyll-feed
  # Use <div data-gist-id="..." data-gist-file="..."></div> instead for performance reasons
  # https://github.com/blairvanderhoof/gist-embed
  # - jekyll-gist

future: true

exclude:
  - "src"
  - "README.md"
  - "LICENSE.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "package.json"
  - "webpack.config.js"
  - "Procfile"
  - "npm-debug.log"
  - "server.js"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      centered_layout: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      draft: false
      centered_layout: true
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
      centered_layout: true
