# Site settings
title: "by @chibicode"
email: shu@chibicode.com
description: "Shu Uesugi's Blog."
baseurl: ""
url: "http://chibicode.com"

# Build settings
markdown: redcarpet
permalink: :title
exclude:
  - "bin"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "post"
    values:
      layout: "post"
