baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
permalink: :title

# This causes an error on GitHub pages, so disabled until 3.0 comes out
# highlighter: null

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."
gems:
  - jekyll-sitemap
  # Use <div data-gist-id="..." data-gist-file="..."></div> instead for performance reasons
  # https://github.com/blairvanderhoof/gist-embed
  # - jekyll-gist

exclude:
  - "README.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "package.json"
  - "webpack.config.js"
  - "webpack.hot.config.js"
  - "bs-config.js"
  - "Procfile"
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      centered_layout: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      draft: false
      centered_layout: true
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
      centered_layout: true
