site_title: "Shu Uesugi"
author:
  name: "Shu Uesugi"
  ja_name: "上杉周作"
  image_url: "/assets/images/shu-uesugi-thumb.jpg"
  twitter_user_name: chibicode
ordered_categories_downcase:
  - "essays"
  - "japanese essays"
